global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["localhost:9100"]

  - job_name: "mysql_exporter"
    static_configs:
      - targets: ["localhost:9104"]

  - job_name: "postgres_exporter"
    static_configs:
      - targets: ["localhost:9187"]

  - job_name: "postgresql"
    static_configs:
      - targets: ["localhost:9187"]

